# Generated by Django 6.0.6 on 2026-06-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productuser',
            options={'verbose_name': 'Product User', 'verbose_name_plural': 'Product Users'},
        ),
    ]
