# Generated by Django 6.0.1 on 2026-07-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_productuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
